---
# defaults file for rhel8_stig
var_aide_scan_notification_email: root@localhost
var_system_crypto_policy: FIPS
sshd_approved_ciphers: aes256-ctr,aes192-ctr,aes128-ctr
sshd_approved_macs: hmac-sha2-512,hmac-sha2-256
inactivity_timeout_value: '900'
var_sudo_timestamp_timeout: '0'
login_banner_text: ^(You[\s\n]+are[\s\n]+accessing[\s\n]+a[\s\n]+U\.S\.[\s\n]+Government[\s\n]+\(USG\)[\s\n]+Information[\s\n]+System[\s\n]+\(IS\)[\s\n]+that[\s\n]+is[\s\n]+provided[\s\n]+for[\s\n]+USG\-authorized[\s\n]+use[\s\n]+only\.[\s\n]+By[\s\n]+using[\s\n]+this[\s\n]+IS[\s\n]+\(which[\s\n]+includes[\s\n]+any[\s\n]+device[\s\n]+attached[\s\n]+to[\s\n]+this[\s\n]+IS\)\,[\s\n]+you[\s\n]+consent[\s\n]+to[\s\n]+the[\s\n]+following[\s\n]+conditions\:(?:[\n]+|(?:\\n)+)\-The[\s\n]+USG[\s\n]+routinely[\s\n]+intercepts[\s\n]+and[\s\n]+monitors[\s\n]+communications[\s\n]+on[\s\n]+this[\s\n]+IS[\s\n]+for[\s\n]+purposes[\s\n]+including\,[\s\n]+but[\s\n]+not[\s\n]+limited[\s\n]+to\,[\s\n]+penetration[\s\n]+testing\,[\s\n]+COMSEC[\s\n]+monitoring\,[\s\n]+network[\s\n]+operations[\s\n]+and[\s\n]+defense\,[\s\n]+personnel[\s\n]+misconduct[\s\n]+\(PM\)\,[\s\n]+law[\s\n]+enforcement[\s\n]+\(LE\)\,[\s\n]+and[\s\n]+counterintelligence[\s\n]+\(CI\)[\s\n]+investigations\.(?:[\n]+|(?:\\n)+)\-At[\s\n]+any[\s\n]+time\,[\s\n]+the[\s\n]+USG[\s\n]+may[\s\n]+inspect[\s\n]+and[\s\n]+seize[\s\n]+data[\s\n]+stored[\s\n]+on[\s\n]+this[\s\n]+IS\.(?:[\n]+|(?:\\n)+)\-Communications[\s\n]+using\,[\s\n]+or[\s\n]+data[\s\n]+stored[\s\n]+on\,[\s\n]+this[\s\n]+IS[\s\n]+are[\s\n]+not[\s\n]+private\,[\s\n]+are[\s\n]+subject[\s\n]+to[\s\n]+routine[\s\n]+monitoring\,[\s\n]+interception\,[\s\n]+and[\s\n]+search\,[\s\n]+and[\s\n]+may[\s\n]+be[\s\n]+disclosed[\s\n]+or[\s\n]+used[\s\n]+for[\s\n]+any[\s\n]+USG\-authorized[\s\n]+purpose\.(?:[\n]+|(?:\\n)+)\-This[\s\n]+IS[\s\n]+includes[\s\n]+security[\s\n]+measures[\s\n]+\(e\.g\.\,[\s\n]+authentication[\s\n]+and[\s\n]+access[\s\n]+controls\)[\s\n]+to[\s\n]+protect[\s\n]+USG[\s\n]+interests\-\-not[\s\n]+for[\s\n]+your[\s\n]+personal[\s\n]+benefit[\s\n]+or[\s\n]+privacy\.(?:[\n]+|(?:\\n)+)\-Notwithstanding[\s\n]+the[\s\n]+above\,[\s\n]+using[\s\n]+this[\s\n]+IS[\s\n]+does[\s\n]+not[\s\n]+constitute[\s\n]+consent[\s\n]+to[\s\n]+PM\,[\s\n]+LE[\s\n]+or[\s\n]+CI[\s\n]+investigative[\s\n]+searching[\s\n]+or[\s\n]+monitoring[\s\n]+of[\s\n]+the[\s\n]+content[\s\n]+of[\s\n]+privileged[\s\n]+communications\,[\s\n]+or[\s\n]+work[\s\n]+product\,[\s\n]+related[\s\n]+to[\s\n]+personal[\s\n]+representation[\s\n]+or[\s\n]+services[\s\n]+by[\s\n]+attorneys\,[\s\n]+psychotherapists\,[\s\n]+or[\s\n]+clergy\,[\s\n]+and[\s\n]+their[\s\n]+assistants\.[\s\n]+Such[\s\n]+communications[\s\n]+and[\s\n]+work[\s\n]+product[\s\n]+are[\s\n]+private[\s\n]+and[\s\n]+confidential\.[\s\n]+See[\s\n]+User[\s\n]+Agreement[\s\n]+for[\s\n]+details\.|I've[\s\n]+read[\s\n]+\&[\s\n]+consent[\s\n]+to[\s\n]+terms[\s\n]+in[\s\n]+IS[\s\n]+user[\s\n]+agreem't\.)$
var_password_pam_remember: '5'
var_password_pam_remember_control_flag: required
var_accounts_passwords_pam_faillock_deny: '3'
var_accounts_passwords_pam_faillock_fail_interval: '900'
var_accounts_passwords_pam_faillock_unlock_time: '0'
var_password_pam_dcredit: '-1'
var_password_pam_dictcheck: '1'
var_password_pam_difok: '8'
var_password_pam_lcredit: '-1'
var_password_pam_maxclassrepeat: '4'
var_password_pam_maxrepeat: '3'
var_password_pam_minclass: '4'
var_password_pam_minlen: '15'
var_password_pam_ocredit: '-1'
var_password_pam_retry: '3'
var_password_pam_ucredit: '-1'
var_password_hashing_algorithm: SHA512
var_account_disable_post_pw_expiration: '35'
var_accounts_maximum_age_login_defs: '60'
var_accounts_minimum_age_login_defs: '1'
var_accounts_password_minlen_login_defs: '15'
var_password_pam_unix_rounds: '5000'
var_accounts_fail_delay: '4'
var_accounts_max_concurrent_login_sessions: '10'
var_accounts_user_umask: '077'
var_auditd_disk_error_action: halt
var_auditd_disk_full_action: halt
var_auditd_action_mail_acct: root
var_auditd_max_log_file_action: syslog
var_auditd_space_left_action: email
var_auditd_space_left_percentage: '25'
rsyslog_remote_loghost_address: logcollector
sysctl_net_ipv6_conf_all_accept_ra_value: '0'
sysctl_net_ipv6_conf_all_accept_redirects_value: '0'
sysctl_net_ipv6_conf_all_accept_source_route_value: '0'
sysctl_net_ipv6_conf_default_accept_ra_value: '0'
sysctl_net_ipv6_conf_default_accept_redirects_value: '0'
sysctl_net_ipv6_conf_default_accept_source_route_value: '0'
sysctl_net_ipv4_conf_all_accept_redirects_value: '0'
sysctl_net_ipv4_conf_all_accept_source_route_value: '0'
sysctl_net_ipv4_conf_all_rp_filter_value: '1'
sysctl_net_ipv4_conf_default_accept_redirects_value: '0'
sysctl_net_ipv4_conf_default_accept_source_route_value: '0'
sysctl_net_ipv4_icmp_echo_ignore_broadcasts_value: '1'
var_removable_partition: /dev/cdrom
var_selinux_policy_name: targeted
var_selinux_state: enforcing
var_postfix_root_mail_alias: system.administrator@mail.mil
var_tftpd_secure_directory: /var/lib/tftpboot
var_sshd_disable_compression: 'no'
var_rekey_limit_size: 1G
var_rekey_limit_time: 1h
sshd_idle_timeout_value: '600'
account_disable_post_pw_expiration: true
accounts_have_homedir_login_defs: true
accounts_logon_fail_delay: true
accounts_max_concurrent_login_sessions: true
accounts_maximum_age_login_defs: true
accounts_minimum_age_login_defs: true
accounts_password_minlen_login_defs: true
accounts_password_pam_dcredit: true
accounts_password_pam_dictcheck: true
accounts_password_pam_difok: true
accounts_password_pam_lcredit: true
accounts_password_pam_maxclassrepeat: true
accounts_password_pam_maxrepeat: true
accounts_password_pam_minclass: true
accounts_password_pam_minlen: true
accounts_password_pam_ocredit: true
accounts_password_pam_pwhistory_remember_password_auth: true
accounts_password_pam_pwhistory_remember_system_auth: true
accounts_password_pam_retry: true
accounts_password_pam_ucredit: true
accounts_password_pam_unix_rounds_password_auth: true
accounts_password_pam_unix_rounds_system_auth: true
accounts_passwords_pam_faillock_deny: true
accounts_passwords_pam_faillock_deny_root: true
accounts_passwords_pam_faillock_interval: true
accounts_passwords_pam_faillock_unlock_time: true
accounts_umask_etc_bashrc: true
accounts_umask_etc_login_defs: true
aide_check_audit_tools: true
aide_scan_notification: true
audit_immutable_login_uids: true
audit_rules_dac_modification_chmod: true
audit_rules_dac_modification_chown: true
audit_rules_dac_modification_fchmod: true
audit_rules_dac_modification_fchmodat: true
audit_rules_dac_modification_fchown: true
audit_rules_dac_modification_fchownat: true
audit_rules_dac_modification_fremovexattr: true
audit_rules_dac_modification_fsetxattr: true
audit_rules_dac_modification_lchown: true
audit_rules_dac_modification_lremovexattr: true
audit_rules_dac_modification_lsetxattr: true
audit_rules_dac_modification_removexattr: true
audit_rules_dac_modification_setxattr: true
audit_rules_execution_chacl: true
audit_rules_execution_chcon: true
audit_rules_execution_semanage: true
audit_rules_execution_setfacl: true
audit_rules_execution_setfiles: true
audit_rules_execution_setsebool: true
audit_rules_file_deletion_events_rename: true
audit_rules_file_deletion_events_renameat: true
audit_rules_file_deletion_events_rmdir: true
audit_rules_file_deletion_events_unlink: true
audit_rules_file_deletion_events_unlinkat: true
audit_rules_immutable: true
audit_rules_kernel_module_loading_delete: true
audit_rules_kernel_module_loading_finit: true
audit_rules_kernel_module_loading_init: true
audit_rules_login_events_lastlog: true
audit_rules_media_export: true
audit_rules_privileged_commands_chage: true
audit_rules_privileged_commands_chsh: true
audit_rules_privileged_commands_crontab: true
audit_rules_privileged_commands_gpasswd: true
audit_rules_privileged_commands_kmod: true
audit_rules_privileged_commands_mount: true
audit_rules_privileged_commands_newgrp: true
audit_rules_privileged_commands_pam_timestamp_check: true
audit_rules_privileged_commands_passwd: true
audit_rules_privileged_commands_postdrop: true
audit_rules_privileged_commands_postqueue: true
audit_rules_privileged_commands_ssh_agent: true
audit_rules_privileged_commands_ssh_keysign: true
audit_rules_privileged_commands_su: true
audit_rules_privileged_commands_sudo: true
audit_rules_privileged_commands_umount: true
audit_rules_privileged_commands_unix_chkpwd: true
audit_rules_privileged_commands_unix_update: true
audit_rules_privileged_commands_userhelper: true
audit_rules_privileged_commands_usermod: true
audit_rules_sudoers: true
audit_rules_sudoers_d: true
audit_rules_suid_privilege_function: true
audit_rules_unsuccessful_file_modification_creat: true
audit_rules_unsuccessful_file_modification_ftruncate: true
audit_rules_unsuccessful_file_modification_open: true
audit_rules_unsuccessful_file_modification_open_by_handle_at: true
audit_rules_unsuccessful_file_modification_openat: true
audit_rules_unsuccessful_file_modification_truncate: true
audit_rules_usergroup_modification_group: true
audit_rules_usergroup_modification_gshadow: true
audit_rules_usergroup_modification_opasswd: true
audit_rules_usergroup_modification_passwd: true
audit_rules_usergroup_modification_shadow: true
auditd_data_disk_error_action: true
auditd_data_disk_full_action: true
auditd_data_retention_action_mail_acct: true
auditd_data_retention_max_log_file_action: true
auditd_data_retention_space_left_action: true
auditd_data_retention_space_left_percentage: true
auditd_local_events: true
auditd_log_format: true
auditd_name_format: true
auditd_overflow_action: true
banner_etc_issue: true
clean_components_post_updating: true
configure_crypto_policy: true
configure_gnutls_tls_crypto_policy: true
configure_kerberos_crypto_policy: true
configure_libreswan_crypto_policy: true
configure_openssl_crypto_policy: true
configure_ssh_crypto_policy: true
configure_strategy: true
configure_tmux_lock_after_time: true
configure_tmux_lock_command: true
coredump_disable_backtraces: true
coredump_disable_storage: true
dconf_gnome_banner_enabled: true
dconf_gnome_disable_ctrlaltdel_reboot: true
dconf_gnome_lock_screen_on_smartcard_removal: true
dconf_gnome_login_banner_text: true
dconf_gnome_screensaver_idle_delay: true
dconf_gnome_screensaver_lock_enabled: true
dir_group_ownership_library_dirs: true
dir_perms_world_writable_root_owned: true
dir_perms_world_writable_sticky_bits: true
disable_ctrlaltdel_burstaction: true
disable_ctrlaltdel_reboot: true
disable_strategy: true
disable_users_coredumps: true
display_login_attempts: true
enable_fips_mode: true
enable_strategy: true
ensure_gpgcheck_globally_activated: true
ensure_gpgcheck_local_packages: true
file_groupowner_var_log: true
file_groupowner_var_log_messages: true
file_groupownership_home_directories: true
file_groupownership_system_commands_dirs: true
file_owner_var_log: true
file_owner_var_log_messages: true
file_ownership_binary_dirs: true
file_ownership_library_dirs: true
file_permissions_binary_dirs: true
file_permissions_etc_audit_auditd: true
file_permissions_etc_audit_rulesd: true
file_permissions_home_directories: true
file_permissions_library_dirs: true
file_permissions_sshd_private_key: true
file_permissions_sshd_pub_key: true
file_permissions_var_log: true
file_permissions_var_log_messages: true
gnome_gdm_disable_automatic_login: true
grub2_audit_argument: true
grub2_audit_backlog_limit_argument: true
grub2_page_poison_argument: true
grub2_pti_argument: true
grub2_slub_debug_argument: true
grub2_vsyscall_argument: true
harden_sshd_ciphers_openssh_conf_crypto_policy: true
harden_sshd_ciphers_opensshserver_conf_crypto_policy: true
harden_sshd_macs_openssh_conf_crypto_policy: true
harden_sshd_macs_opensshserver_conf_crypto_policy: true
high_complexity: true
high_disruption: true
high_severity: true
kernel_module_atm_disabled: true
kernel_module_bluetooth_disabled: true
kernel_module_can_disabled: true
kernel_module_cramfs_disabled: true
kernel_module_sctp_disabled: true
kernel_module_tipc_disabled: true
low_complexity: true
low_disruption: true
low_severity: true
medium_complexity: true
medium_disruption: true
medium_severity: true
mount_option_boot_nosuid: true
mount_option_dev_shm_nodev: true
mount_option_dev_shm_noexec: true
mount_option_dev_shm_nosuid: true
mount_option_home_noexec: true
mount_option_home_nosuid: true
mount_option_nodev_nonroot_local_partitions: true
mount_option_nodev_remote_filesystems: true
mount_option_nodev_removable_partitions: true
mount_option_noexec_remote_filesystems: true
mount_option_noexec_removable_partitions: true
mount_option_nosuid_remote_filesystems: true
mount_option_nosuid_removable_partitions: true
mount_option_tmp_nodev: true
mount_option_tmp_noexec: true
mount_option_tmp_nosuid: true
mount_option_var_log_audit_nodev: true
mount_option_var_log_audit_noexec: true
mount_option_var_log_audit_nosuid: true
mount_option_var_log_nodev: true
mount_option_var_log_noexec: true
mount_option_var_log_nosuid: true
mount_option_var_tmp_nodev: true
mount_option_var_tmp_noexec: true
mount_option_var_tmp_nosuid: true
no_empty_passwords: true
no_reboot_needed: true
package_abrt_removed: true
package_aide_installed: true
package_audit_installed: true
package_fapolicyd_installed: true
package_firewalld_installed: true
package_gssproxy_removed: true
package_iprutils_removed: true
package_opensc_installed: true
package_policycoreutils_installed: true
package_rsyslog_installed: true
package_sendmail_removed: true
package_tmux_installed: true
package_tuned_removed: true
package_usbguard_installed: true
package_vsftpd_removed: true
patch_strategy: true
postfix_client_configure_mail_alias: true
reboot_required: true
require_emergency_target_auth: true
require_singleuser_auth: true
restrict_strategy: true
root_permissions_syslibrary_files: true
rsyslog_encrypt_offload_actionsendstreamdriverauthmode: true
rsyslog_encrypt_offload_actionsendstreamdrivermode: true
rsyslog_encrypt_offload_defaultnetstreamdriver: true
rsyslog_remote_access_monitoring: true
rsyslog_remote_loghost: true
security_patches_up_to_date: true
selinux_policytype: true
selinux_state: true
service_auditd_enabled: true
service_autofs_disabled: true
service_fapolicyd_enabled: true
service_firewalld_enabled: true
service_kdump_disabled: true
service_rngd_enabled: true
service_rsyslog_enabled: true
service_sshd_enabled: true
service_usbguard_enabled: true
set_password_hashing_algorithm_logindefs: true
skip_ansible_lint: true
sshd_disable_compression: true
sshd_disable_empty_passwords: true
sshd_disable_gssapi_auth: true
sshd_disable_kerb_auth: true
sshd_disable_root_login: true
sshd_disable_user_known_hosts: true
sshd_disable_x11_forwarding: true
sshd_do_not_permit_user_env: true
sshd_enable_strictmodes: true
sshd_enable_warning_banner: true
sshd_print_last_log: true
sshd_rekey_limit: true
sshd_set_idle_timeout: true
sshd_set_keepalive_0: true
sshd_use_strong_rng: true
sshd_x11_use_localhost: true
sssd_certificate_verification: true
sssd_enable_smartcards: true
sssd_offline_cred_expiration: true
sudo_remove_no_authenticate: true
sudo_remove_nopasswd: true
sudo_require_reauthentication: true
sudoers_validate_passwd: true
sysctl_fs_protected_hardlinks: true
sysctl_fs_protected_symlinks: true
sysctl_kernel_core_pattern: true
sysctl_kernel_dmesg_restrict: true
sysctl_kernel_kexec_load_disabled: true
sysctl_kernel_kptr_restrict: true
sysctl_kernel_perf_event_paranoid: true
sysctl_kernel_randomize_va_space: true
sysctl_kernel_unprivileged_bpf_disabled: true
sysctl_kernel_yama_ptrace_scope: true
sysctl_net_core_bpf_jit_harden: true
sysctl_net_ipv4_conf_all_accept_redirects: true
sysctl_net_ipv4_conf_all_accept_source_route: true
sysctl_net_ipv4_conf_all_rp_filter: true
sysctl_net_ipv4_conf_all_send_redirects: true
sysctl_net_ipv4_conf_default_accept_redirects: true
sysctl_net_ipv4_conf_default_accept_source_route: true
sysctl_net_ipv4_conf_default_send_redirects: true
sysctl_net_ipv4_icmp_echo_ignore_broadcasts: true
sysctl_net_ipv4_ip_forward: true
sysctl_net_ipv6_conf_all_accept_ra: true
sysctl_net_ipv6_conf_all_accept_redirects: true
sysctl_net_ipv6_conf_all_accept_source_route: true
sysctl_net_ipv6_conf_default_accept_ra: true
sysctl_net_ipv6_conf_default_accept_redirects: true
sysctl_net_ipv6_conf_default_accept_source_route: true
sysctl_user_max_user_namespaces: true
tftpd_uses_secure_mode: true
unknown_strategy: true
usbguard_generate_policy: true
wireless_disable_interfaces: true
xwindows_remove_packages: true
