---
- hosts: test
  remote_user: papa
  become: yes
  become_method: sudo

  tasks:

    - name: Ensure rsyslog is at the latest version
      yum:
        name: rsyslog
        state: present

    - name: Ensure rsyslog is enabled and running
      service:
        name: rsyslog
        state: started
        enabled: yes

    - name: Copy the rsyslog client configuration file.
      template:
        src: template/rsyslog.conf.j2
        dest: /etc/rsyslog.conf
        owner: root
        group: root
        mode: 0644
      notify: Restart Rsyslog

  handlers:
    - name: Restart Rsyslog
      service:
        name: rsyslog
        state: restarted
    
...
